### PR TITLE
Feature/default dataset newest

### PR DESCRIPTION
**Pull request by jefferis**
* @romainFr could you review?

### CODE REVIEW

**Comment by jefferis** [comment]
NB I think that the public neuprint server has updated to 1.1 but we need still need to run tests agains 1.0.1 => set neuprint_dataset = "hemibrain:v1.0.1" on travis.

**Comment by romainFr** [comment]
Thanks @jefferis , looks good. Just one question: why do you think we need to run the tests against 1.0.1, vs updating the tests for 1.1 (happy to help with that if needed)?

**Comment by jefferis** [comment]
The tests can be updated but I didn’t necessarily want to do that on this PR. Also from all the churn I’m seeing, I’m not sure 1.1 is a stable release just yet, so I’d rather wait to redo tests until it is.

**Comment by romainFr** [comment]
Makes sense, this is good for merging then. My understanding is that v1.1 being available on the public server officially sets it as the stable version for the upcoming articles and ends the churn, but it might be safe to wait a few more days. I'll start a PR to get started on updating tests and the latest metadata tweaks for 1.1.

**Comment by jefferis** [comment]
@romainFr @alexanderbates a note that this is now merged! It will a result in a change in end user behaviour as hemibrain v1.1 will now be the default.

**Pull request merged**
