### PR TITLE
Feature/flexible ids

### PR DESCRIPTION
**Pull request by jefferis**
This adds support for flexible custom queries for all functions that take body ids as input. You can do things like:

```
neuprint_get_adjacency_matrix(inputids='DA2 lPN', outputids='DL4 adPN')
# or
pnkc=neuprint_get_adjacency_matrix(inputids='name:mPN', outputids='/KC.*')
```

### CODE REVIEW

**Comment by jefferis** [comment]
@romainFr / @alexanderbates I think this is a nice addition. It would be great if you could give it a try. You can install like so:

```
devtools::install_github('natverse/neuprintr@feature/flexible-ids')
```

**Comment by jefferis** [comment]
@mmc46 @lisa-marin if you also have the chance to test that would be nice.

**Comment by mmc46** [comment]
It is working fine for me, including with the regex for multiple types
```
da1pn_conn = neuprint_connection_table("/DA1.*PN", prepost = "PRE", roi = "AL(R)", all_segments = F)
```

**Comment by jefferis** [comment]
Thanks a lot @mmc46. I'm in a hurry to get this one as https://github.com/flyconnectome/hemibrainr/pull/6 also depends so I've gone ahead and merged now.

**Pull request merged**
