### PR TITLE
WIP : wrappers for path related functions

### PR DESCRIPTION
**Pull request by romainFr**
To pull all paths of a certain length range or all the shortest paths between two bodies.
 
For now I just wrapped the queries for now, I still need to add a nice output, so it's not ready for merging.

### CODE REVIEW

**Comment by jefferis** [comment]
Hi @romainFr thanks for this start. @SridharJagannathan and I will be working seriously on the repo from start of next week. To assist with development we have often found it helpful to create feature branches on the main repo (i.e. natverse/neuprintr in this case) rather than working with PRs on your own repos. The reason is that three of us can interleave commits on a feature branch here, whereas for a PR hosted in your repo, we can only merge or comment. I've sent you an invite for this repo. I think you should also add yourself as an author rather than contributor.

**Comment by jefferis** [comment]
Of course you can still continue to make small self-contained PRs as before.

**Comment by romainFr** [comment]
Both functions now output a data frame with columns "to", "from", "weight", "name.to", "name.from", which should be easily parsable by most network visualization tools.

**Comment by romainFr** [comment]
One thing that one still might want to add is the option to restrict the paths within a given ROI (or set of ROIs)

**Comment by romainFr** [comment]
Tests/examples should be added, but I'm going to merge as it's working/useful (and I'll start working off natverse/neuprintr branches from now on)

**Pull request merged**
